# Site settings
title: Goddard Finn
email: me@goddardfinn.com
description: "Describing your movie!"
baseurl: "/goddard-finn"
url: "http://goddardfiin.com"
twitter_username: goddardfinn

# Build settings
markdown: kramdown
permalink: :title

actors: ["one", "two", "three", "four"]
actors_name: { "one": "Andreys", "two": "Jonathan <br> Brugh", "three": "Simon <br> Johnson", "four": "Louis" }
