# Site settings
title: Goddard Finn
email: me@goddardfinn.com
description: "Describing your movie!"
baseurl: "/goddard-finn"
url: "http://goddardfiin.com"
twitter_username: goddardfinn

# Build settings
markdown: kramdown
permalink: :title

actors: ["one", "two", "three", "four", "five", "six"]
actors_name: {
  "one": "Andreys <br> Sukhomlinov",
  "two": "Kate <br> Simmonds",
  "three": "Sheena <br> Langguth",
  "four": "Simon <br> Johnson",
  "five": "Thomas <br> Sainsbury",
  "six": "Sam <br> Bunkall"
}
