# Site settings
title: Goddard Fiin
email: me@goddardfiin.com
description: "Describing your movie!"
baseurl: "/goddard-fiin"
url: "http://goddardfiin.com"
twitter_username: goddardfiin

# Build settings
markdown: kramdown
permalink: pretty
